# Generated by Django 5.2.7 on 2025-10-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='collaboration_type',
            field=models.CharField(choices=[('Open Source', 'Open Source'), ('Startup Idea', 'Startup Idea'), ('College Project', 'College Project'), ('Learning Project', 'Learning Project'), ('Freelance', 'Freelance')], default='Learning Project', max_length=50),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='estimated_timeline',
            field=models.CharField(blank=True, help_text='Expected duration (e.g., 2 months, ongoing)', max_length=100),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='location',
            field=models.CharField(blank=True, help_text='City or country (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='looking_for',
            field=models.CharField(default=None, help_text='Who are you looking for? (e.g., Frontend Developer, UI Designer)', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='project_description',
            field=models.TextField(default='', help_text='Briefly describe your project idea and goals.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='project_title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='required_skills',
            field=models.CharField(default='', help_text='Skills you expect collaborators to have (e.g., Python, Django, React)', max_length=250),
            preserve_default=False,
        ),
    ]
