# Generated by Django 5.2.7 on 2025-10-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_No',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
