# Generated by Django 5.2.7 on 2025-10-30 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0005_profile_contact_no_profile_contact_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='Need',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='estimated_timeline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='looking_for',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='project_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='required_skills',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
