# Generated by Django 5.2.7 on 2025-10-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0006_alter_collaborationrequest_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationrequest',
            name='Need',
            field=models.CharField(default='Not specified', max_length=150),
        ),
    ]
