# Generated by Django 5.2.7 on 2025-10-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0007_alter_collaborationrequest_need'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='Need',
        ),
    ]
