# Generated by Django 5.2.7 on 2025-10-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0009_expert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expert',
            old_name='email',
            new_name='email_id',
        ),
    ]
