# Generated by Django 5.2.7 on 2025-10-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0010_rename_email_expert_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='expert_images/'),
        ),
    ]
