# Generated by Django 5.2.7 on 2025-10-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0011_expert_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
