# Generated by Django 5.1.6 on 2025-10-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
