# Generated by Django 5.1.6 on 2025-10-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_alter_customuser_linkedin_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Language', models.CharField(max_length=120)),
                ('code', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('review', 'Review'), ('error', 'Error'), ('share', 'share')], default='', max_length=20)),
                ('Comment', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('developer', 'developer'), ('collaborater', 'collaborater')], default='student', max_length=20),
        ),
    ]
