# Generated by Django 5.2.7 on 2025-10-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0004_developerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='experience_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('developer', 'Developer'), ('collaborator', 'Collaborator')], default='student', max_length=20),
        ),
    ]
