# Generated by Django 5.2.7 on 2025-10-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0005_alter_customuser_experience_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='experience_level',
        ),
    ]
