# Generated by Django 5.2.7 on 2025-10-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0006_remove_customuser_experience_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='github_username',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkedin_url',
        ),
    ]
