# Generated by Django 5.2.7 on 2025-10-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0007_remove_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.FileField(upload_to='projects/'),
        ),
    ]
