# Generated by Django 5.2.7 on 2025-10-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0009_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Comment',
        ),
    ]
