# Generated by Django 5.2.7 on 2025-10-23 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0011_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='role',
            new_name='Need',
        ),
    ]
