# Generated by Django 5.2.7 on 2025-10-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0012_rename_role_snippet_need'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='Language',
            new_name='Programming_Language',
        ),
    ]
