# Generated by Django 5.2.7 on 2025-10-30 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0013_rename_language_snippet_programming_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='Comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='Programming_Language',
            new_name='programming_language',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='Need',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='name',
        ),
        migrations.AddField(
            model_name='snippet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snippet',
            name='need',
            field=models.CharField(choices=[('review', 'Review'), ('error', 'Error'), ('share', 'Share')], default='share', max_length=20),
        ),
    ]
